### ISSUE TITLE
Milestone2: Understanding sea ice data products

### ISSUE THREAD

**Issue by shospital** [polarwatch/internship24#6]
__To do2__
- [x] Tien to complete reading the article
- [x] Sunny to complete reading the article 
- [x] Tien to come up with few data summaries/analysis from the article 

__Deliverables__

- [x] Summary of the article
- [x] jupyter notebook with data summary and visualization
- [x] Activity report (briefly describing what you have done)

__To do1__

- [x] Tien to study PolarWatch catalog and come up with questions
- [x] Sunny to go over the polarwatch products and discuss questions with Tien\
- [x] Tien to choose a data product (sea ice concentration)
- [x] Tien to run https://github.com/polarwatch/code-gallery/tree/main/working-with-sea-ice-conc-data and understand the metadata structure
- [x] Tien to search 3-5 sea ice concentration related journals
- [x] Sunny to work with Tien to choose a journal

**Comment by tntly** [comment]
Dataset selected: https://polarwatch.noaa.gov/catalog/ice-sq-nh-nsidc-cdr-v4/preview/?dataset=monthly&var=cdr_seaice_conc_monthly&time_min=2023-12-01T00:00:00Z&time_max=2023-12-01T00:00:00Z&proj=epsg3413&colorBar=KT_ice,,,0,1,
