### ISSUE TITLE
Milestone3: Compute climatology of sea ice concentration

### ISSUE THREAD

**Issue by shospital** [polarwatch/internship24#7]
- [x] Sunny to provide a python code snippet that load data into memory
- [x] Sunny to provide dates and frequency for climatology and how to present in the map
- [x] Sunny to provide a general structure of data summary report 
- [x] Sunny to provide trend info

**Comment by shospital** [comment]
```
import xarray as xr

server = "https://polarwatch.noaa.gov/erddap/griddap"
dataset_id = "ERDDAP_DATASET_ID"

full_URL = '/'.join([server, dataset_id])
ds = xr.open_dataset(full_URL, chunks={"time": "auto"})
ds = ds.sel(time=slice('2024-01-01', '2024-01-07'))

```

**Comment by shospital** [comment]
Frequency: weekly 
Climatology date range: 1991-2020
Questions:
- compare weekly means of sea ice concentration to the current year sea ice concentration
- compute anomalies and trends for 2023 and what were the weeks that show significant difference?

**Comment by shospital** [comment]
temporal trends article and sample codes at https://medium.com/@jaydharpure2007/exploring-temporal-trends-analyzing-time-series-and-gridded-data-with-python-50eac2a13354

@tntly let me know if you can access the article.

**Comment by tntly** [comment]
Thank you, @shospital. I’ve completed the analysis of the anomalies and trends and am currently working on the t-test sections. I’ve uploaded the milestone 3 notebook to my branch if you want to review the plots I’ve finished so far.

**Comment by shospital** [comment]
@tntly In the notebook, the sea ice concentration says (%), but it's proportion 0-1.
